[package]
name = "rebase-migrations"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.32"
walkdir = "2.4.0"
git2 = "0.18.2"
regex = "1.11.1"
rustpython-parser = "0.4.0"

[dev-dependencies]
tempfile = "3.10.1"
